// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace demo1.Migrations
{
    [DbContext(typeof(PaypalDbContext))]
    [Migration("20200916134955_initTable")]
    partial class initTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("PaypalToken", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("access_token")
                        .HasColumnType("TEXT");

                    b.Property<string>("app_id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<int>("expires_in")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nonce")
                        .HasColumnType("TEXT");

                    b.Property<string>("scope")
                        .HasColumnType("TEXT");

                    b.Property<string>("token_type")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("PaypalToken");
                });
#pragma warning restore 612, 618
        }
    }
}
